# Generated by Django 4.2.2 on 2023-10-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('', 'Selecciona el tipo de usuario'), ('cliente_externo', 'Cliente externo'), ('comerciante_local', 'Comerciante local'), ('productor', 'Productor'), ('consultor', 'Consultor'), ('transportista', 'Transportista')], default='', max_length=50, verbose_name='Tipo de Usuario'),
        ),
    ]
