# Generated by Django 4.2.2 on 2023-11-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0003_auction_listing_comments_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='category',
            field=models.CharField(choices=[('UV', 'Uvas'), ('BM', 'Books, Moves & Music'), ('EL', 'Electronics'), ('CO', 'Collectibles & Art'), ('HG', 'Home & Garden'), ('SG', 'Sporting Goods'), ('TH', 'Toys & Hobbies'), ('BI', 'Business & Industrial'), ('HB', 'Health & Beauty'), ('OT', 'Others')], default='OT', help_text='If not specified it will be set as Others', max_length=2),
        ),
    ]
