# Generated by Django 4.2.2 on 2023-11-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0005_alter_auction_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='category',
            field=models.CharField(choices=[('UV', 'Uvas'), ('PL', 'Platanos'), ('FR', 'Frutillas'), ('NA', 'Naranjas'), ('CE', 'Cerezas'), ('MA', 'Mandarinas'), ('FB', 'Frambuesas'), ('PI', 'Piñas'), ('AR', 'Arandanos')], default='OT', help_text='If not specified it will be set as Others', max_length=2),
        ),
    ]
