# Generated by Django 4.2.2 on 2023-11-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0006_alter_auction_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='category',
            field=models.CharField(choices=[('UV', 'Uvas'), ('PL', 'Platanos'), ('FR', 'Frutillas'), ('NA', 'Naranjas'), ('CE', 'Cerezas'), ('MA', 'Mandarinas'), ('FB', 'Frambuesas'), ('PI', 'Piñas'), ('OT', 'Otros')], default='OT', help_text='Si no se especifica se auto asigna como otros', max_length=2),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='img_url',
            field=models.ImageField(blank=True, help_text='Optional', null=True, upload_to='tienda'),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='starting_bid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bids',
            name='highest_bid',
            field=models.IntegerField(default=0),
        ),
    ]
