# Generated by Django 4.2.2 on 2023-11-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0007_alter_auction_listing_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='tienda'),
        ),
    ]
